# Generated by Django 3.2.9 on 2021-11-16 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desciption',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='book',
            old_name='rate',
            new_name='nota',
        ),
    ]
