# Generated by Django 3.2.9 on 2021-11-17 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapi', '0002_auto_20211116_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
